-- liquibase formatted sql

--changelog Volkov:1
CREATE TABLE notification_task (
  id BIGINT GENERATED by default as identity not null,
  chat_id BIGINT NOT NULL,
  notification VARCHAR(255) NOT NULL,
 notification_send_date TIMESTAMP WITHOUT TIME ZONE NON NULL,
  CONSTRAINT "pk" PRIMARY KEY (id)
);